change_history_table: ${SF_CHANGE_HISTORY_TABLE:SCHEMACHANGE.CHANGE_HISTORY}
snowflake_account: ${SNOWFLAKE_ACCOUNT}
snowflake_user: ${SNOWFLAKE_USER}
snowflake_role: ${SNOWFLAKE_ROLE}
snowflake_warehouse: ${SNOWFLAKE_WAREHOUSE}
snowflake_database: ${SNOWFLAKE_DATABASE}
snowflake_schema: GOLD
snowflake_password: ${SNOWFLAKE_PASSWORD}
vars: var.yaml