CREATE SCHEMA IF NOT EXISTS {{ sf_schema }};
CREATE OR REPLACE TABLE {{ sf_database }}.{{ sf_schema }}.SALES_RAW_GOLD_test_1
(
    SALE_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    SALE_DATE DATE,
    QUANTITY INT,
    UNIT_PRICE FLOAT,
    STORE_ID VARCHAR,
    _INSERTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
