name: Deploy to PROD
 
on:
  push:
    branches:
      - prod
 
jobs:
  schemachange-prod:
    runs-on: ubuntu-latest
    environment: snowflake_CICD_prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
 
      - name: Install schemachange
        run: pip install schemachange
 
      - name: Deploy Bronze
        run: |
          schemachange -f bronze/migrations/scripts \
            -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            -u ${{ secrets.SNOWFLAKE_USER }} \
            -r ${{ secrets.SNOWFLAKE_ROLE }} \
            -w ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
            -d ${{ secrets.SNOWFLAKE_DATABASE }} \
            -c bronze/migrations/config/schemachange-config.yml \
            -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
            -v bronze/migrations/var.yaml
 
      - name: Deploy Silver
        run: |
          schemachange -f silver/migrations/scripts \
            -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            -u ${{ secrets.SNOWFLAKE_USER }} \
            -r ${{ secrets.SNOWFLAKE_ROLE }} \
            -w ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
            -d ${{ secrets.SNOWFLAKE_DATABASE }} \
            -c silver/migrations/config/schemachange-config.yml \
            -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
            -v silver/migrations/var.yaml
 
      - name: Deploy Gold
        run: |
          schemachange -f gold/migrations/scripts \
            -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            -u ${{ secrets.SNOWFLAKE_USER }} \
            -r ${{ secrets.SNOWFLAKE_ROLE }} \
            -w ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
            -d ${{ secrets.SNOWFLAKE_DATABASE }} \
            -c gold/migrations/config/schemachange-config.yml \
            -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
            -v gold/migrations/var.yaml
