name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'bronze/migrations/**'
  workflow_dispatch:

jobs:
  deploy-bronze-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Install dependencies
        run: pip install pyyaml schemachange

      - name: Deploy bronze changes
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE_DEV: ${{ secrets.SF_DATABASE_DEV }}  # Optional override
          SF_SCHEMA_BRONZE: ${{ secrets.SF_SCHEMA_BRONZE }}  # Optional override
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Step 1: Parsing variables from bronze-var.yml"
          vars=$(python $GITHUB_WORKSPACE/parse_vars.py $GITHUB_WORKSPACE/bronze/migrations/bronze-var.yml)
          echo "Parsed vars: $vars"
          database_name=$(echo "$vars" | python -c "import json, sys; print(json.loads(sys.stdin.read())['database_name'])")
          schema_name=$(echo "$vars" | python -c "import json, sys; print(json.loads(sys.stdin.read())['schema_name'])")
          echo "Extracted database_name: $database_name"
          echo "Extracted schema_name: $schema_name"
          # Override with secrets if set
          database_name="${SF_DATABASE_DEV:-$database_name}"
          schema_name="${SF_SCHEMA_BRONZE:-$schema_name}"
          echo "Final database_name: $database_name"
          echo "Final schema_name: $schema_name"
          echo "Step 2: Running schemachange with vars: $vars"
          schemachange \
            -f "$GITHUB_WORKSPACE/bronze/migrations/scripts" \
            -a "$SF_ACCOUNT" \
            -u "$SF_USERNAME" \
            -r "$SF_ROLE" \
            -w "$SF_WAREHOUSE" \
            -d "$database_name" \
            -c "$database_name.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table \
            --config-folder "$GITHUB_WORKSPACE/bronze/migrations/config" \
            --vars "$vars"
